### ISSUE TITLE
Registering a project domain

### ISSUE THREAD

**Issue by dhimmel** [cognoma/cognoma#1]
We've gone with the name Project Cognoma, which combines the words cognition and carcinoma. Here we'll throw out ideas for domain names.

**Comment by dhimmel** [comment]
# cogno.ma

`cogno.ma` is a natural first choice. [`.ma`](https://en.wikipedia.org/wiki/.ma) is the top level domain for Morocco.

Potential registrars include:
- [Netim](http://www.netim.com/domain-name/ma-domain.html) -- $40 per year ([possible coupons](https://www.retailmenot.com/view/netim.com))
- [Gandi](https://www.gandi.net/domain) for $86
- [INWX](https://www.inwx.com/en/domain/check) for €50.34
- [Marcaria](https://www.marcaria.com) $68 per year with long term options
- [101domain](https://www.101domain.com) for $69 per year

**Comment by cgreene** [comment]
Apparently .ma requires a local contact. This is offered as a service by at least Netim. The coupons available do not work. Total cost comes to ~$55 which the lab can cover via a grant that we have from the Gordon and Betty Moore Foundation if you decide to go that route. We'd need to acknowledge: This projected is supported in part by a grant from the Gordon and Betty Moore Foundation (GBMF 4552) under the data-driven discovery initiative.

**Comment by dcgoss** [comment]
How about cognoma.org?

**Comment by dhimmel** [comment]
It looks like cognoma.org was recently registered with namecheap. @dcgoss I assume that was you? We will want to control the domain name under a Greene Lab account for longevity reasons. So if we do go with cognoma.org would you be willing to transfer the domain -- we would reimburse you?

In the meantime, can we get some opinions on which domain (cognoma.org or cogno.ma) people prefer? Cost is not an issue.

**Comment by dcgoss** [comment]
It was only $10 so I bought it to be safe. If we decide not to use it that's totally fine. Transfer is no problem for me.

**Comment by cgreene** [comment]
@dcgoss thanks for snapping it up before it got away! I am pretty sure that we can get you reimbursed for it as well. I am supportive of the .org domain or .ma, whichever the team favors - and we can put them on a lab account so that we keep renewing them as long as the service is active.

**Comment by dhimmel** [comment]
Okay I created a [Twitter poll](https://twitter.com/dhimmel/status/750716159973003264) which will be active for the next 24 hours. We'll then reconvene based on the feedback we receive.

**Comment by cgreene** [comment]
Is it possible to create a poll via a PR for people who don't tweet?

**Comment by dhimmel** [comment]
> Is it possible to create a poll via a PR for people who don't tweet?

Can people without Twitter just leave a comment here noting their preference?

**Comment by dcgoss** [comment]
Haha, this is the exact problem Pickle was made for. One thing to consider is that having a Moroccan domain may hurt search rankings in the US. Also in my opinion having the full "cognoma" before the extension shows the name more clearly than .ma. You want people used to saying the full name instead of saying "cogno dot ma".

**Comment by cgreene** [comment]
If only we knew someone who could get us early access to https://getpickleapp.com/. _cough_ _cough_

**Comment by dhimmel** [comment]
The results of [the poll](https://twitter.com/dhimmel/status/750716159973003264) are in:

> ![cognoma domain Twitter poll results](https://cloud.githubusercontent.com/assets/1117703/16663938/16447a62-444c-11e6-905f-428834e173bd.png)

cognoma.org was the clear favorite. @cgreene can you coordinate the namecheap domain transfer/reimbursement with @dcgoss?

**Comment by cgreene** [comment]
Thanks @dcgoss! Send along receipt and we'll figure out reimbursement!

**Comment by dcgoss** [comment]
No need for reimbursement - it's my gift to science! :)

**Comment by cgreene** [comment]
http://cognoma.org lives! Thanks @dcgoss! Repo at http://github.com/cognoma/cognoma.github.io if someone wants to update it :)

**Comment by dhimmel** [comment]
Did anyone register `cognoma` on Twitter? See https://twitter.com/ProjectCognoma/status/819925407923372032.
