### ISSUE TITLE
Frontend Technology

### ISSUE THREAD

**Issue by awm33** [cognoma/cognoma#12]
Did the frontend team agree on a frontend tech stack?

The backend is being designed as a rest API, so I assume a single page app? Angular? React?

I use Angular 1.x at work and have used it for personal projects. If you all want to use it, I can help people get started if they'd like.

Also, assuming some frontend javascript framework is powering it, what would serve up that static content? Django? A webserver like nginx? Usually, you want to place something like nginx in front of you app server, it could also serve the static content. We could use nginx to server the static content and forward `/api/` traffic to the django REST API. Could also forward a path to neo4j if you want to avoid cross site scripting. Nginx also has some rate limiting plugins.

**Comment by cgreene** [comment]
We use Angular 1.X in our lab, so this would make it easier for our group to maintain this. Unless there is a strong reason to choose another technology I'd lean towards Angular 1.X or 2.X (only if 2.X is more valuable from a learning point of view though).

@awm33's description of nginx serves static & forwards /api/ to REST is our preferred setup. I like the idea of also using nginx to forward to neo4j for the hetnet component. Thanks!

**Comment by dhimmel** [comment]
Direct future discussion on this topic to https://github.com/cognoma/frontend/issues/3. Cheers!
