### ISSUE TITLE
link to access the data?

### ISSUE THREAD

**Issue by tkhunkhe** [cognoma/cognoma#14]
Can someone tell me where to find the link to access the data please? I can't recall where we have it. Thanks!

**Comment by mp8** [comment]
https://zenodo.org/record/56735/files/gbm_classifier_data.tar.gz

**Comment by gwaybio** [comment]
Hi @tkhunkhe Here is the [database](https://genome-cancer.ucsc.edu/proj/site/xena/datapages/?cohort=TCGA%20Pan-Cancer%20%28PANCAN%29)

From this database, I use the following files

``` bash
# Downloads data from UCSC Xena
# https://genome-cancer.ucsc.edu/proj/site/xena/datapages/?cohort=TCGA%20Pan-Cancer%20(PANCAN)

# 1) RNAseq data
wget --directory-prefix 'data/' https://genome-cancer.ucsc.edu/download/public/\
xena/TCGA/TCGA.PANCAN.sampleMap/HiSeqV2                                                                                                                                               

 # 2) Clinical data
 wget --directory-prefix 'data/' https://genome-cancer.ucsc.edu/download/public/\
xena/TCGA/TCGA.PANCAN.sampleMap/PANCAN_clinicalMatrix

# 3) Mutation data
wget --directory-prefix 'data/' https://genome-cancer.ucsc.edu/download/public/\
xena/TCGA/TCGA.PANCAN.sampleMap/PANCAN_mutation
```

I have also noticed some issues regarding version control in [UCSC Xena](http://xena.ucsc.edu/). Specifically, files that I have worked with in the past have changed pretty dramatically. @dhimmel is working on getting [git LFS](https://git-lfs.github.com/) up and running so we can supersede the ucsc versioning (or lack thereof).

To work with the data I have been using for my personal work:

``` bash
# All data is publicly available and downloaded from UCSC Xena
# https://genome-cancer.ucsc.edu/proj/site/xena/datapages/?cohort=TCGA%20Pan-Cancer%20(PANCAN)

# Because the database is continously updated and to ensure reproducibility,
# access data from zenodo cached download.

# RNAseq and Clincal data were downloaded on 8 March 2016
# Mutation data was downloaded on 12 June 2015

url=https://zenodo.org/record/56735/files/gbm_classifier_data.tar.gz
wget --directory-prefix 'data/' $url

# Extract
tar -zxvf data/gbm_classifier_data.tar.gz
```

**Comment by dhimmel** [comment]
# Preliminary data subsets

I created some preliminary subsets of the data. They derive from two datasets:
- `expression-matrix` is a sample × gene matrix indicating a gene's expression level for a given sample. This dataset will be the feature/X/predictor dataset for Project Cognoma.
- `mutation-matrix` is a sample × gene matrix indicating whether a gene is mutated for a given sample. Select columns (or unions of several columns) in this dataset will be the status/y/outcome dataset for Project Cognoma. 

The subsets are [available here](https://github.com/dhimmel/cancer-data/tree/8c7a8023d3be838c77e1dfa8139ec5c345039fa0/data/subset).

For subsets that are small enough to fit in your browser, see:
- [`expression-matrix-small.tsv`](https://github.com/dhimmel/cancer-data/blob/8c7a8023d3be838c77e1dfa8139ec5c345039fa0/data/subset/expression-matrix-small.tsv)
- [`mutation-matrix-small.tsv`](https://github.com/dhimmel/cancer-data/blob/8c7a8023d3be838c77e1dfa8139ec5c345039fa0/data/subset/mutation-matrix-small.tsv)

**Comment by dhimmel** [comment]
I [posted the full datasets](https://doi.org/10.6084/m9.figshare.3487685.v2) to figshare. You can download them from their and begin playing around with machine learning.

**Comment by dhimmel** [comment]
The most recent data is available from https://doi.org/10.6084/m9.figshare.3487685.

This info is now available on the `cognoma/cancer-data` README, so will close this issue.
