### ISSUE TITLE
Cognoma Logo

### ISSUE THREAD

**Issue by gwaybio** [cognoma/cognoma#21]
I don't like looking at the bland/blank icon for the cognoma github organization. Anyone creative want to design a logo?

**Comment by dhimmel** [comment]
Yes, we'll need a logo for the GitHub organization and website. We'll also need a favicon. Perhaps the same person wants to design both?

It would also be great if the logo could start as a vector image (SVG perhaps) that we could export to whatever needed resolution.

**Comment by tkhunkhe** [comment]
Uh, obviously my artistic skill is terrible. But here is some idea throwing in there.  :D Please feel free to take the idea and make it better somehow (because I don't how, haha)
![logo](https://cloud.githubusercontent.com/assets/10778112/17039265/97f4abba-4f67-11e6-9ba8-d9d552c596fd.jpg)

**Comment by dhimmel** [comment]
@cgreene can you make this the organization photo (maybe crop it to be more zoomed in).

We can let others make submissions as well, and then vote which we like best. But until then, I think we should use @tkhunkhe's logo!

**Comment by cgreene** [comment]
@dhimmel Done!

**Comment by tkhunkhe** [comment]
![image](https://cloud.githubusercontent.com/assets/10778112/17219552/c1948164-54b9-11e6-901b-b13026d1d763.png)
a favicon. Ugh, I don't know how to upload this, but here is the link to the file.
[link to favicon.ico file](https://github.com/tkhunkhe/cognoma/blob/master/favicon.ico)

**Comment by stephenshank** [comment]
Submitted a (very simple) [pull request](https://github.com/cognoma/cognoma.github.io/pull/1) for this, as well as a [video explaining it](https://www.youtube.com/watch?v=oKlW_dSUrb8&feature=youtu.be) that will hopefully be instructive for people wanting to submit pull requests on their own. @dhimmel can you point to any front end people who can review the PR? @tkhunkhe would you be willing to provide feedback on whether or not you found the video helpful?

**Comment by tkhunkhe** [comment]
@stephenshank The [video](https://www.youtube.com/watch?v=oKlW_dSUrb8&feature=youtu.be) was very helpful! Especially the last two minutes, I was able to follow along and understand the picture of what is going on. I I like the energy too 😄 👍  Thanks!

**Comment by dhimmel** [comment]
> @dhimmel can you point to any front end people who can review the PR?

I merged https://github.com/cognoma/cognoma.github.io/pull/1. Awesome work with the video!

We'll keep this issue open in case anyone wants to submit additional designs. But for now we have some cool logos. Awesome work @tkhunkhe and @stephenshank.

**Comment by dhimmel** [comment]
Closing since we have a logo. Thx @tkhunkhe. Can reopen if anyone signals interest.

**Comment by stephenshank** [comment]
I have a friend whose father does graphic design. I asked a while back about a logo, and recently received the following black and white image. I also added some color gradients, messing around with GIMP. Figured I'd share and see what everyone thought.
![cognomasmall](https://cloud.githubusercontent.com/assets/8673708/19476916/ab6d9908-9509-11e6-80b9-177e977d8644.jpg)
![cognomabluesmall](https://cloud.githubusercontent.com/assets/8673708/19476925/b31d6e58-9509-11e6-98be-877ca0947bb1.jpg)

**Comment by dhimmel** [comment]
Wow those are awesome!

> I have a friend whose father does graphic design.

Did you want to share his name so we can recognize his contribution? Maybe even get him on the GitHub!

**Comment by stephenshank** [comment]
> Did you want to share his name so we can recognize his contribution?

His name is Jeff Riegler, and I think it would be great to recognize him.

I can submit a PR to this repository with the image in SVG format, if this is desirable.

**Comment by dhimmel** [comment]
> I can submit a PR to this repository with the image in SVG format

Sounds good. Can you override the git author using:

```
git commit --author="Jeff Riegler <jeffs_email@address.com>"
```

> I can submit a PR to this repository with the image in SVG format

Yea SVG and a high res PNG.

**Comment by dhimmel** [comment]
@stephenshank the SVG logo would be nice -- is it ready for a pull request?

**Comment by dhimmel** [comment]
Closing as I think Jeff Riegler's logo is awesome. Thanks to @stephenshank, it's now available in the [`media/logo`](https://github.com/cognoma/cognoma/tree/33770f95b8ca5b3ac217a87e8133918b160d7d5b/media/logo) directory.
