### ISSUE TITLE
July 19–26 Project Cognoma Acknowledgements

### ISSUE THREAD

**Issue by dhimmel** [cognoma/cognoma#23]
Here is the list of contributions over the past week that I highlighted at [tonight's meetup](https://www.meetup.com/DataPhilly/events/232785717/).
## [`cognoma/cognoma`](https://github.com/cognoma/cognoma)

Now up to 40 introductions on https://github.com/cognoma/cognoma/issues/2.

@tkhunkhe made a project logo. See https://github.com/cognoma/cognoma/issues/21#issuecomment-234388780. We're still looking for a favicon and alternative logos if anyone is interested.
## [`cognoma/sandbox`](https://github.com/cognoma/sandbox)

We're up to 17 commits with people testing out how to do pull requests. See https://github.com/cognoma/sandbox/commits/master. Keep messing around in the sanbox if you would like.
## [`cognoma/frontend`](https://github.com/cognoma/frontend)

@BobMiller discussed reaching out to the Philly JavaScript meetup for more frontend contributors. See https://github.com/cognoma/frontend/issues/4.

Which version of angular to use was discussed by @gwaygenomics, @awm33, @cgreene, and @mhuyck. See https://github.com/cognoma/frontend/issues/3.

@gwaygenomics created a learning resource discussion. See https://github.com/cognoma/frontend/issues/2.

`cognoma/frontend` is looking for maintainers.
## [`cognoma/cognoma.github.io`](https://github.com/cognoma/cognoma.github.io)

@dcgoss transferred the cognoma.org domain to the Greene Lab, who will facilitate longterm registration. @cgreene created a landing page for cognoma.org (see https://github.com/cognoma/cognoma.github.io and https://github.com/cognoma/cognoma/issues/1).

`cognoma/cognoma.github.io` is looking for maintainers (overlaps with frontend).
## [`cognoma/django-cognoma`](https://github.com/cognoma/django-cognoma)

Discussion continued on renaming the repository with @dcgoss, @awm33, @aelkner, and @cgreene all providing input. See https://github.com/cognoma/django-cognoma/issues/10.

@dcgoss created a backend learning guide. See https://github.com/cognoma/django-cognoma/issues/15.

Discussion on which Python version to use began. See https://github.com/cognoma/django-cognoma/issues/14.

@BobMiller and @ramjac discussed the data needs of the frontend. See https://github.com/cognoma/django-cognoma/issues/13.

@jhonjairoroa87 suggested travis-ci for continuous integration and automated testing. See https://github.com/cognoma/django-cognoma/issues/9.
## [`cognoma/machine-learning`](https://github.com/cognoma/machine-learning)

@gwaygenomics added a [machine learning notebook](http://nbviewer.jupyter.org/github/cognoma/machine-learning/blob/892c6994d0f57c671611781d1b96cbba31ee3c7e/1.TCGA-MLexample.ipynb) using the cancer-data. @stephenshank reviewed the pull request and found missing import statements. :+1: to @stephenshank for executing the code. See https://github.com/cognoma/machine-learning/pull/10.

@dhimmel and @cgreene theorized about the potential confounding effect of general mutation load. See https://github.com/cognoma/machine-learning/issues/8.

@awm33 opened an issue on specifying what the task data payload should look like: See https://github.com/cognoma/machine-learning/issues/9.

@bevinahally and @hhummel discussed good learning resources for machine learning. See https://github.com/cognoma/machine-learning/issues/7.

@yl565 and @hhummel created tables of possible classification algorithms. See https://github.com/cognoma/machine-learning/issues/5.

@autokad listed methods for feature engineering See https://github.com/cognoma/machine-learning/issues/1.

@ejsegall discussed saving performance-related parameters. See https://github.com/cognoma/machine-learning/issues/6.

`cognoma/machine-learning` is still looking for maintainers.
## [`cognoma/cancer-data`](https://github.com/cognoma/cancer-data)

@clairemcleod reviewed and merged the first cancer-data pull request. She reported an OS compatibility issue with the conda environment in cancer-data (:+1: for running the code). We found a workaround where we stopped specifying build numbers and also only specific explicit dependencies. See https://github.com/cognoma/cancer-data/pull/7.

@dhimmel converted gene symbols in the expression dataset to entrez gene identifiers. @clairemcleod reviewed and committed the pull request. See https://github.com/cognoma/cancer-data/pull/8.

Discussion continued on how to convert genes in the mutation dataset to entrez gene. Closer to rectifying the symbols-as-dates issue. See https://github.com/cognoma/cancer-data/issues/4.

The Xena Browser team helped answer our questions on their [Google Group Mailing List](https://groups.google.com/forum/?fromgroups#!forum/ucsc-cancer-genomics-browser). Thanks @jingchunzhu and Mary Goldman!
## July 26 Meetup strategic goals

Let's get more code review. It's encouraged to be detailed and note if you don't understand. See for example https://github.com/scikit-learn/scikit-learn/pull/7071 (in general check out pull requests from starred open source projects).

Take initiative. Assign yourself tasks. Get involved with the code. Our goal for tonight is that everyone who wants to contribute leaves with a takehome task. It will be two weeks until our next meeting. So try to leave with some part of the project.

**Comment by dcgoss** [comment]
This is great, thanks for the effort👍
