### ISSUE TITLE
2016 Rocky Mountain Bioinformatics Conference Abstract

### ISSUE THREAD

**Issue by dhimmel** [cognoma/cognoma#34]
I wrote an abstract, due later today, on Project Cognoma for the [Rocky Mountain Bioinformatics Conference](https://www.iscb.org/rocky2016-program/rocky2016-call-abstracts). Anyone who has contributed (though accepted pull requests) to a Cognoma repository other than sandbox is listed as an author. I based the author ordering on #33 / [`contrib/contributor-summary.tsv`](https://github.com/cognoma/cognoma/blob/459d69c9db11dc87980fd44ee75803e998107a46/contrib/contributor-summary.tsv).

***

**Title:** The Cognoma Collaborative creates a webapp to predict cancer mutations from gene expression

**Authors:** Daniel Himmelstein, Gregory Way, Andrew Madonna, Alan Elkner, Benjamin Dolly, Yichuan Liu, Claire McLeod, Derek Goss, Haitao Cai, Chris Fuller, Robert Paul Miller, Nabeel Sarwar, Branka Jokanovic, Mans Singh, Stephen Shank, Joel Eden, Karin Wolok, Casey Greene

**Abstract:**

Precision oncology requires that we functionally categorize cancers into treatment-relevant subtypes. The predominant approach—characterizing tumors based solely on actionable mutations—struggles to detect complex changes in gene or pathway function. Alternatively, genome-wide expression profiles provide a comprehensive reflection of aberrant cellular states resulting from mutation events. Therefore, we embarked on Project Cognoma to translate between gene expression and mutation in cancer.

Cognoma is an open-source/citizen-science philanthropy being developed as a collaboration between the Greene Lab at Penn and the DataPhilly and Code for Philly meetups. This arrangement leverages the collective fullstack expertise of our diverse contributor base. Hitherto, hundreds of individuals have attended Cognoma meetups, and more than fifty have gotten involved on GitHub (https://github.com/cognoma/cognoma). Our priorities are "everyone learns something new" and "putting machine learning in the hands of cancer biologists."

Our product is cognoma.org, a webapp that makes it easy to build mutation status classifiers from gene expression on 7,306 TCGA samples representing 33 cancer types. The publicly available dataset contains RNA-seq gene expression for 20,530 genes, non-silent mutation calls for 21,940 genes, and sample attributes such as the patient's disease, age, sex, and survival. Cognoma enables a cancer biologist to assign each sample a mutation status based on one or more selected genes. Next, a disciplined classifier is trained using gene expression and sample attributes as features. As output, the user receives the importance of each feature—offering insight into the molecular effects of their chosen mutation—as well as a mutation scores for samples—which potentially identify hidden responders to targeted pharmacotherapies.

**License:** This abstract is published under a [CC BY 4.0 License](https://creativecommons.org/licenses/by/4.0/).

**Comment by dhimmel** [comment]
@htcai & @mans2singh, you're currently identified by your GitHub username. If you would like me to use your name instead, respond here with the name you'd like me to use by 6:30 pm. However no pressure -- anonymous contributions are obviously welcome.

**Comment by dhimmel** [comment]
Tagging all authors: @dhimmel, @gwaygenomics, @awm33, @aelkner, @yl565, @clairemcleod, @bdolly, @KarinSpiderwoman, @dcgoss, @keenleo, @BobMiller, @htcai, @mans2singh, @stephenshank, @NabeelSarwar, @brankaj, @cgreene.

If for some reason you would like not to be an author, please also let me know here or privately by 6:30 pm. I am planning to put all affiliations as the DataPhilly Meetup.

**Comment by htcai** [comment]
Thanks, Daniel! Please use my name **Haitao Cai**. I am excited to be listed as a contributor.

**Comment by stephenshank** [comment]
Thanks so much Daniel!! I am also very excited to be included!

**Comment by gwaybio** [comment]
Pumped about the progress on the work!

I think it is important to emphasize that this is a Presentation at a Bioinformatics Conference. Eventually we will be generating a publication so that we can publicize this work to our **Cancer Biologist** user base.

There is still plenty of time for people not listed to make important contributions!

**Comment by cgreene** [comment]
Echoing the above comments :tada:! For this audience, describing the cognoma project, participation model, etc, are important. Let's keep our eyes on the overall goal of a server useful for and used by cancer biologists! :100:

**Comment by beelze-b** [comment]
Same here. You can list me as Nabeel Sarwar.

**Comment by brankaj** [comment]
Thank you for including me! It's a great idea to put DataPhilly as the affiliation. I am thrilled to be a part of this project and I hope I can contribute more.

**Comment by dhimmel** [comment]
> deadline 6:30 pm today

The submission deadline has been [extended to Friday](https://twitter.com/ProfLHunter/status/783038666855755777), so I'll hold off submitting until after tomorrow's meetup.

**Comment by BobMiller** [comment]
Dan (@dhimmel),

Its very generous of you to include us all as authors! Thanks!

One request, could you list my name as Robert Paul Miller, instead of Bob Miller. Bob/Robert Miller is such a common name, all us Bob Millers get mixed up sometimes.

**Comment by mans2singh** [comment]
Hey Folks:  Please include me as Mans Singh.  Mans

**Comment by dhimmel** [comment]
I submitted the abstract. I used the most recent contribution info from https://github.com/cognoma/cognoma/pull/36. @joeleden was added.

:tada: You may all have gotten emails.

**Comment by dhimmel** [comment]
Just got notified that the abstract was accepted for a 10 minute presentation.

🍾  to Cognoma!

**Comment by dhimmel** [comment]
Gave the presentation today, which is [now on YouTube](https://youtu.be/wN-9bWakQWQ). See also the [slides](http://slides.com/dhimmel/rocky) and [abstract](https://www.iscb.org/cms_addon/conferences/rocky2016/track/oral.php#OP18). Thanks everyone who's helped us reach this point. Excited for the future.

**Comment by htcai** [comment]
Excited too!
