### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by awm33** [cognoma/cognoma#41]
Since this is across every production code repo, decided to place this here. We need centralized to have logging in order to diagnose issues.

Here are some options:
- ELK (Elasticsearch Logstash Kibana) - I use this at work. It's nice, but we would require one or more elasticsearch servers and running a logstash agent on each container instance (a containers instance has many containers).
- Elasticsearch and Kibana (sans logstash) - Send log data [using an elasticsearch handler](https://github.com/cmanaha/python-elasticsearch-logger) skipping logstash, removing one moving part.
- AWS CloudWatch Logs - Send logs to CloudWatch using [the watchtower package](https://github.com/kislyuk/watchtower). CloudWatch Logs are hosted and cheap ($0.50 per GB processed) but I've heard the UI is clunky compared to Kibana.
- [Loggly](https://www.loggly.com/) - Fully hosted. Would be at least $50 a month. I've used this before. The UI was amazing and it had built in alerts based on log searches. The issue was price. I had a decent log volume and would always peak.
- [Logentries](https://logentries.com/pricing/) - Fairly similar to Loggly.
- [LogDNA](https://logdna.com/) - New guy in town. Similar hosted model to the two above, but uses purely volume based pricing starting at $1.25 per GB.

I don't see us having high volume, at least to start.

If we want to go the hosted route, we can try for discounted or free hosting in exchange for logos or something.

For the ones using elasticsearch, AWS does have an elasticsearch service that includes Kibana. We would still need to pay the associated resource costs (EC2, EBS, etc).

I'm leaning towards elasticsearch+kibana, since logstash is really only needed if the logs are not formatted already (like sys logs). Maybe trying out CloudWatch Logs to see how the UI is.

Hosted is probably also worth exploring. The cheapest elasticsearch EC2 with decent memory is $52 a month, and that's for one server, not a cluster.

**Comment by dhimmel** [comment]
Outside of my domain of expertise. Tagging @cgreene and @dcgoss.

**Comment by cgreene** [comment]
If we use Raven (or another sentry compatible logger), we can store errors at sentry. We have an account there with high capacity due.

**Comment by awm33** [comment]
Looks like Sentry is good for errors / crash reports. I've gotten recommendations of it for frontend error reporting. So I think we should go ahead with using it for frontend and possibly the python backend.

But from [Sentry](https://sentry.io/vs/logging/)

> Sentry works with your application logging infrastructure, often integrating directly. It does not replace the need for those logs, and it's also not a destination for things that aren't actionable errors or crashes.

I might play with CloudWatch Logs, but otherwise I might go ahead with setting up a single elasticsearch+kibana instance and go from there.

**Comment by cgreene** [comment]
@awm33 : Agree that it is not a comprehensive logging solution. 👍 on your plan.

**Comment by dcgoss** [comment]
I have about zero experience in this sort of area, so I trust your judgement

**Comment by dcgoss** [comment]
Logging is currently taking place in the containers. This issue should be closed.
