### ISSUE TITLE
Task Queue Manager

### ISSUE THREAD

**Issue by awm33** [cognoma/cognoma#9]
Based on some previous disussion in https://github.com/cognoma/cognoma/issues/4 and https://github.com/cognoma/cognoma/issues/5 I'm opening up an issue specifically for the task queue / management.

I think it would make sense to make it a separate repository within the cognoma org.

I've used a bunch of other open source job queues over the past few and they all had issues. After some colleagues suggested just using mysql or postgres with SQS, I was hooked. Simple queues and postgres are also easy to scale and maintain, plus you get to apply postgres knowledge from the app/API.

I proposed one in https://github.com/cognoma/cognoma/issues/5 based on a design I've been using for a while. I originally wrote it in Node.js and ported to Clojure. It's usually around 400-600 lines for a basic version (no parent/child jobs) and exposes it as a service. The service keeps issues from arising like queueing the same job twice, or pulling a job more than once (distributed queues are at least once delivery).

It uses Postgres plus a queue. I've used it with IronMQ (do not use :) ), SQS, and Google Pub/Sub. It could also be used with other queues or locking mechanisms such as a Redis Queue or Redlock. For SQS and Google Cloud Pub/Sub, I made an abstraction class, so picking one doesn't necessarily lock you in.

SQS also has some open source alternatives that are API compatible.
- https://github.com/adamw/elasticmq - The team at my company uses this in the dev environment and for testing
- https://github.com/Comcast/cmb - For larger production environments. I think this is being contributed to Openstack.

A unique column can be used to prevent a job from be queued twice. The submitter would construct a string key that uniquely identifies a job (like "user-234-geneset-2387"). The unique column is combined with task_type into a unique partial index (postgres shinning here) where status is queued or in_progress. run_at and schedule columns can be used to create scheduled or recurring tasks.

Some questions:
- Is the main Cognoma instance run by the Greenelab going to be on a cloud platform? Like AWS or Google Cloud Platform. Then that platforms queue service may be ideal as a first option.
- Would we want this as an HTTP service? Probably using http://www.django-rest-framework.org/ I like doing it this way as it keeps the job queue code centeralized and queuers and workers just hit an HTTP endpoint. Could also hit it from different languages, if that become beneficial.
- If we want to run within the django app process, could we drop in it? Eg include the routes from this class. I don't know Django or that rest library well enough yet to answer that. Assuming we could, is that more ideal than a separate HTTP process?

If project the leads like this approach, I could start on an MVP and see if others have some ideas on improvement or more features.

**Comment by cgreene** [comment]
"Is the main Cognoma instance run by the Greenelab going to be on a cloud platform? Like AWS or Google Cloud Platform. Then that platforms queue service may be ideal as a first option." -> Yes. We don't have physical hardware for it. It will almost certainly one of those two providers. If we can keep it vendor agnostic that would be ideal, but I understand if we gain substantial time by selecting one of their existing queues.

HTTP service -> This sounds good to me. I like the idea of allowing different languages to hit it. This would provide more flexibility in the implementation for containerized workers.

Within django -> This I don't know. It could potentially be written as a reusable django app (though I would want to know if some of the celery integrations already provide this). @awm33 and others, could you share what you think some of the benefits and drawbacks would be?

Also - do you have suggestions for a repository name?

**Comment by awm33** [comment]
@cgreene Cool. I think keeping an abstraction interface can help keep it vendor agnostic, even if we only have one interface implementation to start.

The pros to having it be it's on django app would be that it could scale and fail independently of the django app powering the frontend and core data models. To start, it could be run on the same server under a different port. It also sounds like you may be using containers (docker?), which makes it pretty easy to set it up on it's own.

Maybe cognoma/task-service ?

**Comment by dhimmel** [comment]
@awm33, yeah I think it would be great to use Docker containers. One aspect of the project is letting our contributors learn technologies that will be important in the future. Docker, I believe, will be.

> Maybe cognoma/task-service?

I created [`cognoma/task-service`](https://github.com/cognoma/task-service) and appointed you as a maintainer on that repo. It's currently empty, so you can add a README/repo description. Do as you see fit.

**Comment by dcgoss** [comment]
+1 for Docker, it's great

**Comment by awm33** [comment]
This had been branched off into https://github.com/cognoma/task-service plus submit task management issues there
